### ISSUE TITLE
Support passing buffer or readablestream to PDFEngine.convert

### ISSUE THREAD

**Issue by shkreios** [cherfia/chromiumly#133]
Thank you for this nice library,
my current use case is that I am preprocessing a word document via [docx-templates](https://www.npmjs.com/package/docx-templates) and don't want to save the output to file system to convert it to PDF and instead directly pipe the output i.e. `Buffer` or `Readablestream` to the `PDFEngine.convert` method. 

# Proposal
Either adding a separate input property or adding a second type to files input. Adding support for attaching `Buffer`/`Readablestream` to FormData i.e. skipping filesystem read inside `injectFiles` if object is `Buffer` or `Readablestream` & directly pushing it to `FormData`.

If this solution is acceptable, i can open a pr if you want.

**Comment by cherfia** [comment]
Thank you for your suggestion and I am glad to hear that you're enjoying using the library. I appreciate your proposal and I think this is a great idea as it would certainly be useful for users who want to skip the file system and directly pipe the output to the `PDFEngine` `convert` method. I welcome your pull request and would be happy to review it once you have submitted it. 

Thank you for taking the time to share your proposal with us, and please let us know if you have any questions or need any assistance with your pull request.

**Comment by cherfia** [comment]
@shkreios Thank you for your suggestion and I am glad to hear that you're enjoying using the library. I appreciate your proposal and I think this is a great idea as it would certainly be useful for users who want to skip the file system and directly pipe the output to the `PDFEngine` `convert` method. I welcome your pull request and would be happy to review it once you have submitted it.

**Comment by scorsi** [comment]
Hello, interested too :)

**Comment by cherfia** [comment]
@scorsi I haven't heard back from @shkreios, but maybe I will just go ahead and do it if it's needed. If you have the time, your contribution is also welcome.

**Comment by cherfia** [comment]
@scorsi @shkreios supports for buffer and readable stream have been added in version [2.5.0](https://github.com/cherfia/chromiumly/releases/tag/v2.5.0). Please test it out and let me know if it meets your needs.
