### ISSUE TITLE
Gotenberg now has Performance Mode For Chromium. Could you please release an update to support this too?

### ISSUE THREAD

**Issue by dananichev** [cherfia/chromiumly#342]
Hello. 

More info about it
https://gotenberg.dev/docs/routes#performance-mode-chromium 

Discussion with how it affects performance
https://github.com/gotenberg/gotenberg/discussions/743

Thanks

**Comment by cherfia** [comment]
Hi @dananichev thank you so much for the update. Yes, will add performance mode support.

**Comment by cherfia** [comment]
@dananichev The performance mode property, which you requested, has been added to version [2.7.0](https://github.com/cherfia/chromiumly/releases/tag/v2.7.0) 🚀
