### ISSUE TITLE
singlePage property not working when converting from xlsx to pdf

### ISSUE THREAD

**Issue by satramcs** [cherfia/chromiumly#360]
Problem statement: I need the entire excel sheet to single page in pdf so that the excel sheet should not broken.
There is a option in libreoffice calc "**Whole sheet export**" (Please refer the screenshot)
![Screenshot 2024-04-03 125545](https://github.com/cherfia/chromiumly/assets/62286308/3f4560f8-cc7d-4587-99fc-53b554bec592)

I need to enable the whole sheet export option while converting the xlsx to pdf.
So I've set the property `singlePage: true` but it doesn't not works.
![Screenshot 2024-04-03 125202](https://github.com/cherfia/chromiumly/assets/62286308/e2b80135-a6dc-4a7c-acc2-915fa4a88022)

Please let me know if there is any other way to enable the **Whole sheet export** option
Sample code:

```
const path = require("path");
const fs = require("fs");

const libre = require("libreoffice-convert");
libre.convertAsync = require("util").promisify(libre.convert);

async function main() {
    const { PDFEngine } = await import("chromiumly");
    const buffer = await PDFEngine.convert({
        files: [path.join(__dirname, "/resources/test-file.xlsx")],
        properties: { singlePage: true },
    });
    fs.writeFileSync(path.join(__dirname, "/resources/test-file.pdf"), buffer);
}

main().catch(function () {
    console.log('Error converting file: ');
});
```

**Comment by cherfia** [comment]
@satramcs Thank you for reporting it. Could you please tell me what version of Gotenberg you're currently using? This is important as the `singlePage` property was introduced starting from Gotenberg version [8.2.0](https://github.com/gotenberg/gotenberg/releases/tag/v8.2.0).

**Comment by satramcs** [comment]
I'm using this [chromiumly 2.9.0](https://www.npmjs.com/package/chromiumly) package.
This package is require gotenberg docker image to be run. As per documentation I'm running `docker run --rm -p 3000:3000 gotenberg/gotenberg:8` this docker image

**Comment by cherfia** [comment]
@satramcs Unfortunately, Gotenberg only supports the `singlePage` property when converting with [Chromium](https://gotenberg.dev/docs/routes#page-properties-chromium). LibreOffice does not have a support for this page property yet 😕  https://gotenberg.dev/docs/routes#page-properties-libreoffice.

**Comment by cherfia** [comment]
The `convert` method in the `PDFEngine` is simply a wrapper for Gotenberg's [LibreOffice convert route](https://gotenberg.dev/docs/routes#page-properties-libreoffice). Currently, the only properties supported are `landscape` and `nativePageRanges`. That is why when using the `singlePage` property in your code, no action occurs because this property is not supported.
```
const buffer = await PDFEngine.convert({
    files: [path.join(__dirname, "/resources/test-file.xlsx")],
    properties: { singlePage: true },
});
```
I hope this helps clarify things.

**Comment by satramcs** [comment]
Thank you for your clarification. Do we have any other solution to export the excel sheet to single page using libreoffice? (any configuration on the docker side)
"**Whole sheet export**" with this option

**Comment by cherfia** [comment]
@satramcs I'm not very knowledgeable about that topic 😅 but perhaps you could find assistance by asking in the [Gotenberg discussions](https://github.com/gotenberg/gotenberg/discussions).

**Comment by cherfia** [comment]
@satramcs Gotenberg introduced a new property LibreOffice `singlePageSheets` that you requested in version [8.4.0](https://github.com/gotenberg/gotenberg/releases/tag/v8.4.0) and it's now supported in chromiumly version [3.1.0](https://github.com/cherfia/chromiumly/releases/tag/v3.1.0) 🚀
