### ISSUE TITLE
Listed formats are not support 

### ISSUE THREAD

**Issue by satramcs** [cherfia/chromiumly#362]
I need support for below file formats
docm, potx, pptm psd, xlsb, xlsm, vsdx, vsd.

Those formats are listed as supported formats in [gotenberg documentation](https://gotenberg.dev/docs/routes#office-documents-into-pdfs-route)
![image](https://github.com/cherfia/chromiumly/assets/62286308/330225b9-51ac-4399-a279-ff9843336e89)

I checked in chromiumly code, mentioned formats are not listed. I'm getting the error `docm is not supported`

Please add the missed supported formats here `src/libre-office/utils/constants.ts`

Sample code
```
async function main() {
    const { PDFEngine } = await import("chromiumly");
    const buffer = await PDFEngine.convert({
        files: [path.join(__dirname, "/resources/test-file.docm")]
    });
    fs.writeFileSync(path.join(__dirname, "/resources/test-file.pdf"), buffer);
}
```

**Comment by cherfia** [comment]
@satramcs I will look into it today, and keep you posted.

**Comment by cherfia** [comment]
@satramcs the LibreOffice extensions, which you requested, have been added to version [2.10.0](https://github.com/cherfia/chromiumly/releases/tag/v2.10.0) 🚀
Please test it out and let me know if it meets your needs 👍

**Comment by cherfia** [comment]
@satramcs Awesome 🚀
