### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by forg002-ctrl** [cherfia/chromiumly#399]
I am encountering an authentication issue while attempting to pass the username and password via an .env file:

GOTENBERG_ENDPOINT=http://gotenberg:3000
GOTENBERG_API_BASIC_AUTH_USERNAME=user
GOTENBERG_API_BASIC_AUTH_PASSWORD=pass

My docker-compose.yml file:
  gotenberg:
    image: gotenberg/gotenberg:8.6.0
    environment:
      GOTENBERG_API_BASIC_AUTH_USERNAME: user
      GOTENBERG_API_BASIC_AUTH_PASSWORD: pass
    command: gotenberg --api-enable-basic-auth
    networks:
      - internal

Despite correctly setting up the environment variables, I consistently receive a 401 Unauthorized error when the application attempts to authenticate using these credentials.

But It works when I change the files like this:

GOTENBERG_ENDPOINT=http://gotenberg:3000
GOTENBERG_API_BASIC_AUTH_USERNAME=user
GOTENBERG_API_BASIC_AUTH_PASSWORD=user

docker-compose.yml:
  gotenberg:
    image: gotenberg/gotenberg:8.6.0
    environment:
      GOTENBERG_API_BASIC_AUTH_USERNAME: user
      GOTENBERG_API_BASIC_AUTH_PASSWORD: user
    command: gotenberg --api-enable-basic-auth
    networks:
      - internal

**Comment by cherfia** [comment]
@forg002-ctrl Thank you for reporting the bug. I will release a fix shortly.

**Comment by cherfia** [comment]
@forg002-ctrl version [3.3.2](https://github.com/cherfia/chromiumly/releases/tag/v3.3.2) has been released with the fix included 🚀  Thanks again and please try it and let me know if it resolves the issue 👍

**Comment by forg002-ctrl** [comment]
@cherfia It works, thanks a lot for quick fix.
