### ISSUE TITLE
Different .env variable name for GROTEBENRB_ENDPOINT

### ISSUE THREAD

**Issue by forg002-ctrl** [cherfia/chromiumly#410]
Hi, I'd like to have another name for GROTENBERG_EDPOINT variable. Long story short, I have three .env variables:
![image](https://github.com/cherfia/chromiumly/assets/75656422/c86bcc80-dd4f-49e2-a7a2-99c1dbf67fda)

I configure them in my main.ts file:
![image](https://github.com/cherfia/chromiumly/assets/75656422/53f2bced-473b-42cf-9d34-4d7432be87cd)

I've configured HtmlConverter as provider for getting it through DI:
![image](https://github.com/cherfia/chromiumly/assets/75656422/67a24c4e-0d88-4e00-8b1a-638a695efc6f)

I get in from DI in the service, where I need to use it:
![image](https://github.com/cherfia/chromiumly/assets/75656422/aa689b30-96b3-493a-bcc6-95cc3259f939)

I get the error:
![image](https://github.com/cherfia/chromiumly/assets/75656422/6cd7fe4b-72cc-4dd1-bb43-931fd00f6964)

**Comment by cherfia** [comment]
@forg002-ctrl If you're using `dotenv` already, you don't actually need to use `Chromiumly.configure()`. Instead, you can simply set up the environment variables as shown [here](https://github.com/cherfia/chromiumly?tab=readme-ov-file#basic-authentication). Or is `GROTENBERG_BASE_URL` used elsewhere in your code where it's not related to` chromiumly`?

**Comment by cherfia** [comment]
@forg002-ctrl I plan to drop support for `config` and `dotenv` in version 4.0.0. Configuration will be done through `Chromiumly.configure()`, allowing users to name their environment variables as they wish 😄  Migration will be simple; users just need to add this method to their code. What do you think? 🤔

**Comment by forg002-ctrl** [comment]
> @forg002-ctrl I plan to drop support for `config` and `dotenv` in version 4.0.0. Configuration will be done through `Chromiumly.configure()`, allowing users to name their environment variables as they wish 😄 Migration will be simple; users just need to add this method to their code. What do you think? 🤔

Hi, I think it's the best way to configure the env variables.

**Comment by cherfia** [comment]
> @forg002-ctrl If you're using `dotenv` already, you don't actually need to use `Chromiumly.configure()`. Instead, you can simply set up the environment variables as shown [here](https://github.com/cherfia/chromiumly?tab=readme-ov-file#basic-authentication). Or is `GROTENBERG_BASE_URL` used elsewhere in your code where it's not related to` chromiumly`?

@forg002-ctrl how about this?
