### ISSUE TITLE
Need to have configuration files for each NODE_ENV variable

### ISSUE THREAD

**Issue by forg002-ctrl** [cherfia/chromiumly#411]
I get this error every time I start my project:
│ WARNING: NODE_ENV value of 'staging' did not match any deployment config file names.                                                            
│ WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode

**Comment by cherfia** [comment]
@forg002-ctrl Thanks for reporting this. It is not an error but just a warning. I'll update chromiumly to suppress this warning message. 👍

**Comment by cherfia** [comment]
@forg002-ctrl I noticed that the warning occurs when you install `chromiumly` along with its optional dependencies (i.e., without using the `--omit=optional` flag). This would include the `config` package, which enforces `Strict Mode`, requiring the presence of a config file related to the Node environment. 👀 

Anyway, the newest version [3.5.0 ](https://github.com/cherfia/chromiumly/releases/tag/v3.5.0) should solve this issue. Could you please try it out and let me know if it resolves it for you?
