### ISSUE TITLE
Sorting when merging

### ISSUE THREAD

**Issue by griprLaaker** [cherfia/chromiumly#505]
We discovered an issue when merging documents on version 3.6.0. All the documents were sent to the merge-endpoint in correct order, and given names based on the index. But Gotenberg sort files alphabetically by filenames, so the files are sorted like this: file1.pdf, file10.pdf, file11.pdf, file2.pdf, file3.pdf etc. And will fail when merging more than 9 files. To correct this we added a patch in chromiumly/dist/pdf-engines/utils/pdf-engines.utils.js line 21: 
`const filename = `file${key.toString().padStart(5, "0")}.pdf`;`
This will add leading 0 before key and will work up to 10000 files which is sufficient for us.
You'll probably find a better solution :-)

**Comment by cherfia** [comment]
Thanks for pointing this out and sharing the fix! I'll make sure to include it in the next release 👍

**Comment by cherfia** [comment]
@griprLaaker Thanks once again for bringing this up! I want to let you know that it has been resolved in [version 3.10.1](https://github.com/cherfia/chromiumly/releases/tag/v3.10.1) 🚀
